service: bookings-consumer

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 128

  stage: dev
  region: us-east-1

functions:
  stream_listener:
    handler: handler.listen
    role: ${ssm:${self:custom.stage}-bookings-stream-consumer-iam-role}
    events:
      - stream: ${ssm:${self:custom.stage}-dynamodb-bookings-streams}
    environment:
      SNS_NOTIFICATIONS_TOPIC: ${ssm:${self:custom.stage}-notifications-topic}

custom:
  stage: ${opt:stage, self:provider.stage}
